from .other import register_other
from .fundraising import register_fundraising
from .questions_and_votes import register_questions_and_votes
from .errors import register_errors
from .language import register_language
from .main_menu import register_main_menu
from .commands import register_commands
from .subscribes import register_subscribes
from .balance_top_up import register_balance_top_up
from .library import register_library
from .polls import register_polls
